### ISSUE TITLE
An "\`example\` property should be multiple of 0.01" occurs for an example value of `154123.99`

### ISSUE THREAD

**Issue by peteraritchie** [stoplightio/vscode-spectral#111]
An "\`example\` property should be multiple of 0.01" occurs for an example value of `154123.99`

**To Reproduce**
1. Given this schema:
```yaml
    Amount:
      type: number
      format: double
      multipleOf: 0.01
      example: 154123.99
```
3. See an error

**Expected behavior**
Expected that a valid example would not result in an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/408620/135874381-41336abf-684c-4794-b98b-15b8b4c68cca.png)

**Environment:**
 - Extension version: [e.g. 0.2.5]
 - VS Code version: [e.g. 1.60.2]
 - Operating System: [e.g. Windows 10]
